const GAME_STATES = {
  MENU: 'MENU',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
};

const RESOLUTION = {
  WIDTH: 1920,
  HEIGHT: 1080,
};

export const MOVEMENT_MULTIPLIER = 3;

const DEBUGGING = false;

const CONFIG = { GAME_STATES, RESOLUTION, MOVEMENT_MULTIPLIER, DEBUGGING };

export default CONFIG;
