const GAME_STATES = {
  MENU: 'MENU',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
};

export const MOVEMENT_MULTIPLIER = 3;

const DEBUGGING = false;

const CONFIG = { GAME_STATES, MOVEMENT_MULTIPLIER, DEBUGGING };

export default CONFIG;
